command: [
  "python",
  "app.py"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"
  - name: "DATABRICKS_SERVING_ENDPOINT"
    valueFrom: "serving_endpoint"
  - name: "SAMPLE_TABLE_PATH"
    value: "steventan.what_if_simulation_apps.wine_data"
  - name: "MLFLOW_TRACKING_URI"
    value: "databricks"
  - name: "INTERPRETER_SERVING_ENDPOINT"
    valueFrom: "interpreter_serving_endpoint"
  - name: "CATALOG"
    value: "steventan"
  - name: "SCHEMA"
    value: "what_if_simulation_apps"
  - name: "VOLUME_UPLOAD_PATH"
    value: "batch_inference_upload"
  - name: "VOLUME_DOWNLOAD_PATH"
    value: "batch_inference_download"
  - name: "DATABRICKS_BATCH_INFERENCE_JOB_ID"
    valueFrom: "batch_inference_job" 